In [81]:
import pandas as pd
import matplotlib.pyplot as plt

In [84]:
import glob, os

In [90]:
files = glob.glob('*.csv')
print (files)

['14-agevolazione-tariffaria-efficienza.csv', '50-sportello-edilizia-efficienza.csv', '23-iscrizione-asili-nido-efficienza.csv', '41-dichiarazione-tari-efficienza.csv', '32-iscrizione-scuola-infanzia-efficienza.csv', '59-appuntamento-edi-urb-efficienza.csv']

In [91]:
df = pd.concat([pd.read_csv(fp, sep=",").assign(New=os.path.basename(fp)) for fp in files])

In [92]:
df

,Efficienza,M,F,18-36,37-51,52+,Totale,New
0,Molto,29.4,33.9,35.0,33.7,17.3,32.0,14-agevolazione-tariffaria-efficienza.csv
1,Abbastanza,60.5,59.9,59.4,60.2,57.7,60.2,14-agevolazione-tariffaria-efficienza.csv
2,Poco,7.1,3.7,3.6,3.9,7.7,4.9,14-agevolazione-tariffaria-efficienza.csv
3,Per niente,0.7,0.4,0.9,0.2,0.0,0.5,14-agevolazione-tariffaria-efficienza.csv
4,Preferisco non rispondere,2.3,2.1,1.1,1.9,17.3,2.4,14-agevolazione-tariffaria-efficienza.csv
0,Molto,20.9,20.0,7.4,29.4,11.1,19.3,50-sportello-edilizia-efficienza.csv
1,Abbastanza,72.2,74.0,88.9,63.5,80.6,70.4,50-sportello-edilizia-efficienza.csv
2,Poco,4.3,6.0,3.7,7.1,2.8,8.5,50-sportello-edilizia-efficienza.csv
3,Per niente,2.6,0.0,0.0,0.0,5.5,1.8,50-sportello-edilizia-efficienza.csv
4,Preferisco non rispondere,0.0,0.0,0.0,0.0,0.0,0.0,50-sportello-edilizia-efficienza.csv
0,Molto,28.9,31.1,30.1,33.9,12.5,30.2,23-iscrizione-asili-nido-efficienza.csv
1,Abbastanza,61.2,63.5,63.8,59.3,50.0,62.8,23-iscrizione-asili-nido-efficienza.csv
2,Poco,7.5,4.7,5.5,5.5,25.0,5.7,23-iscrizione-asili-nido-efficienza.csv
3,Per niente,0.7,0.1,0.3,0.0,0.0,0.4,23-iscrizione-asili-nido-efficienza.csv
4,Preferisco non rispondere,1.7,0.6,0.3,1.3,12.5,0.9,23-iscrizione-asili-nido-efficienza.csv
0,Molto,20.9,19.0,15.2,24.1,18.9,18.9,41-dichiarazione-tari-efficienza.csv
1,Abbastanza,67.9,64.8,63.7,64.4,69.2,67.2,41-dichiarazione-tari-efficienza.csv
2,Poco,7.0,9.5,12.1,7.3,6.3,1.6,41-dichiarazione-tari-efficienza.csv
3,Per niente,1.9,1.6,4.5,0.0,1.9,8.3,41-dichiarazione-tari-efficienza.csv
4,Preferisco non rispondere,2.3,5.1,4.5,4.2,3.7,4.0,41-dichiarazione-tari-efficienza.csv
0,Molto,27.1,31.8,34.5,32.2,5.6,29.7,32-iscrizione-scuola-infanzia-efficienza.csv
1,Abbastanza,61.9,62.6,58.6,61.9,55.5,61.7,32-iscrizione-scuola-infanzia-efficienza.csv
2,Poco,7.5,3.1,4.9,4.3,5.6,5.4,32-iscrizione-scuola-infanzia-efficienza.csv
3,Per niente,1.4,0.0,0.0,0.3,5.6,0.6,32-iscrizione-scuola-infanzia-efficienza.csv
4,Preferisco non rispondere,2.1,2.5,2.0,1.3,27.7,2.6,32-iscrizione-scuola-infanzia-efficienza.csv
0,Molto,21.0,36.7,30.0,23.8,29.0,24.2,59-appuntamento-edi-urb-efficienza.csv
1,Abbastanza,70.2,60.0,60.0,71.4,64.5,67.1,59-appuntamento-edi-urb-efficienza.csv
2,Poco,7.9,3.3,10.0,4.8,6.5,8.0,59-appuntamento-edi-urb-efficienza.csv
3,Per niente,0.9,0.0,0.0,0.0,0.0,0.7,59-appuntamento-edi-urb-efficienza.csv
4,Preferisco non rispondere,0.0,0.0,0.0,0.0,0.0,0.0,59-appuntamento-edi-urb-efficienza.csv

In [63]:
df= pd.read_csv("23-iscrizione-asili-nido-efficienza.csv", sep=",")
df

                  Efficienza     M     F  18-36  37-51   52+  Totale
0                      Molto  28.9  31.1   30.1   33.9  12.5    30.2
1                 Abbastanza  61.2  63.5   63.8   59.3  50.0    62.8
2                       Poco   7.5   4.7    5.5    5.5  25.0     5.7
3                 Per niente   0.7   0.1    0.3    0.0   0.0     0.4
4  Preferisco non rispondere   1.7   0.6    0.3    1.3  12.5     0.9

In [64]:
t = df.T

In [65]:
t.reset_index(inplace=True)

In [66]:
t

        index      0           1     2           3                          4
0  Efficienza  Molto  Abbastanza  Poco  Per niente  Preferisco non rispondere
1           M   28.9        61.2   7.5         0.7                        1.7
2           F   31.1        63.5   4.7         0.1                        0.6
3       18-36   30.1        63.8   5.5         0.3                        0.3
4       37-51   33.9        59.3   5.5           0                        1.3
5         52+   12.5          50    25           0                       12.5
6      Totale   30.2        62.8   5.7         0.4                        0.9

In [67]:
t.rename(columns=t.iloc[0], inplace=True)

In [68]:
t.drop(t.index[0], inplace=True)

In [69]:
t['tipo']="Iscrizione Asili Nido"

In [70]:
t

,Efficienza,Molto,Abbastanza,Poco,Per niente,Preferisco non rispondere,tipo
1,M,28.9,61.2,7.5,0.7,1.7,Iscrizione Asili Nido
2,F,31.1,63.5,4.7,0.1,0.6,Iscrizione Asili Nido
3,18-36,30.1,63.8,5.5,0.3,0.3,Iscrizione Asili Nido
4,37-51,33.9,59.3,5.5,0,1.3,Iscrizione Asili Nido
5,52+,12.5,50,25,0,12.5,Iscrizione Asili Nido
6,Totale,30.2,62.8,5.7,0.4,0.9,Iscrizione Asili Nido

In [71]:
df_2= pd.read_csv("32-iscrizione-scuola-infanzia-efficienza.csv", sep=",")

In [75]:
t_2= df_2.T
t_2.reset_index(inplace=True)
t_2.rename(columns=t_2.iloc[0], inplace=True)
t_2.drop(t_2.index[0], inplace=True)

In [76]:
t_2['tipo']="Iscrizione Scuola Infanzia"

In [77]:
t_2

,Efficienza,Molto,Abbastanza,Poco,Per niente,Preferisco non rispondere,tipo
1,M,27.1,61.9,7.5,1.4,2.1,Iscrizione Scuola Infanzia
2,F,31.8,62.6,3.1,0,2.5,Iscrizione Scuola Infanzia
3,18-36,34.5,58.6,4.9,0,2,Iscrizione Scuola Infanzia
4,37-51,32.2,61.9,4.3,0.3,1.3,Iscrizione Scuola Infanzia
5,52+,5.6,55.5,5.6,5.6,27.7,Iscrizione Scuola Infanzia
6,Totale,29.7,61.7,5.4,0.6,2.6,Iscrizione Scuola Infanzia

In [78]:
final = pd.concat([t,t_2])

In [79]:
final

,Efficienza,Molto,Abbastanza,Poco,Per niente,Preferisco non rispondere,tipo
1,M,28.9,61.2,7.5,0.7,1.7,Iscrizione Asili Nido
2,F,31.1,63.5,4.7,0.1,0.6,Iscrizione Asili Nido
3,18-36,30.1,63.8,5.5,0.3,0.3,Iscrizione Asili Nido
4,37-51,33.9,59.3,5.5,0,1.3,Iscrizione Asili Nido
5,52+,12.5,50,25,0,12.5,Iscrizione Asili Nido
6,Totale,30.2,62.8,5.7,0.4,0.9,Iscrizione Asili Nido
1,M,27.1,61.9,7.5,1.4,2.1,Iscrizione Scuola Infanzia
2,F,31.8,62.6,3.1,0,2.5,Iscrizione Scuola Infanzia
3,18-36,34.5,58.6,4.9,0,2,Iscrizione Scuola Infanzia
4,37-51,32.2,61.9,4.3,0.3,1.3,Iscrizione Scuola Infanzia
5,52+,5.6,55.5,5.6,5.6,27.7,Iscrizione Scuola Infanzia
6,Totale,29.7,61.7,5.4,0.6,2.6,Iscrizione Scuola Infanzia

In [80]:
final.to_csv("test.csv", index=None)